-- PostgreSQL
-- ALTER TABLE conversations
-- ALTER COLUMN user_name SET NOT NULL,
-- ALTER COLUMN employer_name SET NOT NULL,
-- ALTER COLUMN message SET NOT NULL,
-- ALTER COLUMN  date_sent SET NOT NULL;

-- MySQL
ALTER TABLE conversations
MODIFY COLUMN user_name varchar(200) NOT NULL,
MODIFY COLUMN employer_name VARCHAR(250) NOT NULL,
MODIFY COLUMN message TEXT NOT NULL,
MODIFY COLUMN  date_sent TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;

